### ISSUE TITLE
[Test]: Routing snapshot test

### ISSUE THREAD

**Issue by he2e2** [BTS-Busan-Trip-Supporter/front-end#23]
## Overview

NavigationBar test

## Tasks

- [x] 내비게이션 바가 잘 렌더링 되는지
- [x] /login과 /my 경로에서는 내비게이션 바가 렌더링 안 되는지
- [x] 메뉴 클릭 시, 활성화 되는지
- [x] 메뉴 클릭 시, router.replace 되는지
