### ISSUE TITLE
[Feat]: Apply changed design to travel-auto page

### ISSUE THREAD

**Issue by he2e2** [BTS-Busan-Trip-Supporter/front-end#44]
## Overview

'알아서 해줘' 페이지 추가된 디자인 반영

## Tasks

- [x] 카드 선택 시, 디테일 카드 출력
- [x] 디테일 카드에서 선택하기 눌렀을 때, 체크 표시 활성화
- [x] 잠시만 기다려 주세요
- [x] 최근 검색
- [x] 리뷰 카드
- [x] 드롭 박스
